### ISSUE TITLE
Float type error

### ISSUE THREAD

**Issue by JasonLing95** [eastgenomics/Ploutos#19]
```
env) jason@jason-ThinkPad-T14-Gen-2i:~/github/Ploutos$ python Ploutos/manage.py runscript populate_db
2022-11-02 16:22:23
DNAnexus login successful
There are 11 projects with
no files so they weren't added to the df
15 projects are no longer in the table as they only contained duplicate files
/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py:619: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  aggregated_file_type_all_projs = states_filled_in.append(
/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py:619: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  aggregated_file_type_all_projs = states_filled_in.append(
/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py:619: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  aggregated_file_type_all_projs = states_filled_in.append(
Exception while running run() in 'scripts.populate_db'
Traceback (most recent call last):
  File "Ploutos/manage.py", line 22, in <module>
    main()
  File "Ploutos/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super().run_from_argv(argv)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super().execute(*args, **options)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/commands/runscript.py", line 283, in handle
    run_script(script_mod, *script_args)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/commands/runscript.py", line 161, in run_script
    exit_code = mod.run(*script_args)
  File "/home/jason/github/Ploutos/Ploutos/scripts/populate_db.py", line 322, in run
    final_dict, file_type_df = queries.orchestrate_get_files(
  File "/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py", line 1612, in orchestrate_get_files
    unique_sum_df = calculate_totals(unique_grouped_df, 'unique')
  File "/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py", line 793, in calculate_totals
    (my_grouped_df['size'] / (2**30) * settings.LIVE_STORAGE_COST_MONTH / days_in_month),
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
numpy.core._exceptions.UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('float64'), dtype('<U6')) -> None
```
Error when running `python manage.py runscript populate_db`. Log above.

**Comment by jethror1** [comment]
fixed in #20
