### ISSUE TITLE
Variable referenced before assignment error

### ISSUE THREAD

**Issue by JasonLing95** [eastgenomics/Ploutos#21]
```
INFO 2022-11-03 10:08:19,195 autoreload 7 140321589143360 Watching for file changes with StatReloader
ERROR 2022-11-03 11:16:02,016 log 7 140321339381504 Internal Server Error: /ploutos/leaderboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/Ploutos/dashboard/views.py", line 974, in leaderboard
    json_chart_data, chart_html = lb_plots.UserPlotFunctions(
  File "/app/Ploutos/scripts/leaderboard_plots.py", line 787, in daily_filter_byusers
    json_chart_data = json.dumps(category_chart_data)
UnboundLocalError: local variable 'category_chart_data' referenced before assignment
```

**Comment by jethror1** [comment]
Fixed in #25
